apiVersion: v1
kind: Secret
metadata:
  name: app-ai-secret
  namespace: goormthon-6
type: Opaque
stringData:
  GPS_API_KEY: "YOUR_GPS_KEY"
  GPS_GEOCODE_URL: "https://maps.googleapis.com/maps/api/geocode/json"
  GPS_REVERSE_GEOCODE_URL: "https://maps.googleapis.com/maps/api/geocode/json"
  GEMINI_API_KEY: "YOUR_GEMINI_KEY"
  GEMINI_MODEL: "gemini-2.5-flash"
  GEMINI_BASE_URL: "https://generativelanguage.googleapis.com"
  TOUR_API_KEY: "YOUR_TOUR_API_KEY"
  TOUR_API_BASE_URL: "https://apis.data.go.kr/B551011/KorService2/locationBasedList2"
  TOUR_API_MOBILE_OS: "ETC"
  TOUR_API_MOBILE_APP: "JejuReVillage"
  TOUR_API_RADIUS_METERS: "3000"
  TOUR_API_NUM_ROWS: "5"
  SOLAPI_BASE_URL: "https://api.solapi.com"
  SOLAPI_API_KEY: "YOUR_SOLAPI_API_KEY"
  SOLAPI_API_SECRET: "YOUR_SOLAPI_API_SECRET"
  SOLAPI_SENDER: "01012345678"
