apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:yourpassword@postgres:5432/jeju_revillage?schema=public"
