apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: goormthon-6

images:
  - name: postgres
    newTag: "15" # FIX ME 원하는 버전으로 수정하세요. 

patches:
  - target:
      kind: Secret
      name: postgres-secret
    patch: |
      - op: replace
        path: /stringData
        value:
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_USER: postgres
          POSTGRES_DB: jeju_revillage
  - target:
      kind: Secret
      name: app-db-secret
    patch: |
      - op: replace
        path: /stringData
        value:
          DATABASE_URL: postgresql://postgres:yourpassword@postgres:5432/jeju_revillage?schema=public
