apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goormthon-6 #FIXME:

resources:
  - frontend.yaml
  - ingress.yaml

images:
  - name: frontend
    newName: your-account-id.dkr.ecr.ap-northeast-2.amazonaws.com/goormthon-6/frontend
    newTag: latest

configMapGenerator:
  - name: frontend-config
    files:
      - frontend-config.json=config/frontend-config.json

generatorOptions:
  disableNameSuffixHash: true
